const mongoose = require("mongoose");


/**
 * job description
 * resume text 
 * self description
 * technical question : [{question,intention,answer}]
 * behavioral question : [{question,intention,answer}]
 * skills gaps : [{skill,importance('low,medium,high'),}]
 * preparation plan: [{day,focus&task,time,description}]
 * Feedback & Suggestions
 * Score Number
 */

const technicalQuestionSchema = new mongoose.Schema( //generated by gemini
    {
        question: {
            type: String,
            required: [true, "Please enter your question"],
        },
        intention: {
            type: String,
            required: [true, "Please enter your intention"],
        },
        answer: {
            type: String,
            required: [true, "Please enter your answer"],
        },
    },{
        _id: false, //no need of id because report will have already a id
    }
);


const behavioralQuestionSchema = new mongoose.Schema( //generated by gemini
    {
        question: {
            type: String,
            required: [true, "Please enter your question"],
        },
        intention: {
            type: String,
            required: [true, "Please enter your intention"],
        },
        answer: {
            type: String,
            required: [true, "Please enter your answer"],
        },
    },{
        _id: false, //no need of id because report will have already a id
    }
);

const skillsGapsSchema = new mongoose.Schema( //generated by gemini
    {
        skill: {
            type: String,
            required: [true, "Please enter your skill"],
        },
        importance: {
            type: String,
            enum: ["low", "medium", "high"],
            required: [true, "Please select your importance"],
        },
    },{
        _id: false
    }
);


const preparationPlanSchema = new mongoose.Schema(
    {
        day: {
            type: Number,
            required: [true, 'Day is required'],
        },
        focus: {
            type: String,
            required: [true, 'Focus is required'],
        },
        task: [{
            type: String,
            required: [true, 'Task is required'],
        }]
    }
);



const reportSchema = new mongoose.Schema(
    {
        jobDescription: {
            type: String,
            required: [true, "Please enter your job description"],
        },
        resume: {
            type: String,
        },
        selfDescription: {
            type: String
        },
        Score: {
            type: Number,
            min: 0,
            max: 100,
            default: 0
        },
        technicalQuestions: [ technicalQuestionSchema ],
        behavioralQuestions: [ behavioralQuestionSchema ],
        skillsGaps: [ skillsGapsSchema ],
        preparationPlan: [ preparationPlanSchema ],

        feedback: {
            type: String,
        },
        suggestions: {
            type: String,
        },
    },{
        timestamps: true
    },
    {
        user:{
            type: mongoose.Schema.Types.ObjectId,
            ref: 'users'
        }
    }
);


const ReportModel = mongoose.model("Report", reportSchema);

module.exports = ReportModel;