const puppeteer = require("puppeteer");

function buildReportHtml(report, { user, selfDescription, jobDescription }) {
  return `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Interview Report</title>
      <style>
        body { font-family: Arial, sans-serif; color: #111; background: #f7f7f7; margin: 0; padding: 30px; }
        .container { max-width: 900px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 18px; box-shadow: 0 18px 40px rgba(0,0,0,0.08); }
        h1, h2, h3, h4 { color: #222; margin: 0 0 12px; }
        h1 { font-size: 32px; }
        h2 { font-size: 24px; border-bottom: 2px solid #ddd; padding-bottom: 8px; margin-top: 28px; }
        h3 { font-size: 20px; }
        p { line-height: 1.65; margin: 0 0 16px; }
        .section { margin-bottom: 24px; }
        .badge { display: inline-block; padding: 6px 12px; border-radius: 999px; background: #50fa7b; color: #111; font-weight: 700; margin-bottom: 12px; }
        .grid { display: grid; gap: 16px; }
        .grid-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
        .card { padding: 18px; border: 1px solid #e4e4e4; border-radius: 14px; background: #fafafa; }
        ul { margin: 0; padding-left: 20px; }
        li { margin-bottom: 10px; }
        .small { font-size: 14px; color: #555; }
        .footer { margin-top: 32px; font-size: 14px; color: #777; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Interview Report</h1>
        <p class="small">Generated for ${user?.username || user?.email || "Candidate"}.</p>

        <div class="section card">
          <h2>Summary</h2>
          <p><strong>Score:</strong> ${report.score ?? "N/A"}/100</p>
          <p><strong>Feedback:</strong> ${report.feedback || "No feedback available."}</p>
          <p><strong>Suggestions:</strong> ${report.suggestions || "No suggestions available."}</p>
        </div>

        <div class="section card">
          <h2>Context</h2>
          <p><strong>Job Description:</strong></p>
          <p>${jobDescription ? jobDescription.replace(/\n/g, "<br />") : "Not provided."}</p>
          <p><strong>Self Description:</strong></p>
          <p>${selfDescription ? selfDescription.replace(/\n/g, "<br />") : "Not provided."}</p>
        </div>

        <div class="section">
          <h2>Skills Gaps</h2>
          <div class="grid grid-2">
            ${report.skillsGaps?.map((gap) => `
              <div class="card">
                <h3>${gap.skill}</h3>
                <p><strong>Severity:</strong> ${gap.importance}</p>
              </div>
            `).join("") || "<p>No skill gaps found.</p>"}
          </div>
        </div>

        <div class="section">
          <h2>Technical Questions</h2>
          ${report.technicalQuestions?.map((item) => `
            <div class="card">
              <h3>${item.question}</h3>
              <p><strong>Why they asked this:</strong> ${item.intention}</p>
              <p><strong>Suggested answer:</strong> ${item.answer}</p>
            </div>
          `).join("") || "<p>No technical questions generated.</p>"}
        </div>

        <div class="section">
          <h2>Behavioral Questions</h2>
          ${report.behavioralQuestions?.map((item) => `
            <div class="card">
              <h3>${item.question}</h3>
              <p><strong>Why they asked this:</strong> ${item.intention}</p>
              <p><strong>Suggested answer:</strong> ${item.answer}</p>
            </div>
          `).join("") || "<p>No behavioral questions generated.</p>"}
        </div>

        <div class="section">
          <h2>Preparation Plan</h2>
          <ul>
            ${report.preparationPlan?.map((item) => `
              <li>
                <strong>Day ${item.day} - ${item.focus}:</strong>
                <ul>${item.tasks?.map((task) => `<li>${task}</li>`).join("")}</ul>
              </li>
            `).join("") || "<li>No plan generated.</li>"}
          </ul>
        </div>

        <div class="footer">
          <p>Generated by FeedCV.</p>
        </div>
      </div>
    </body>
  </html>
  `;
}

async function createPdfFromReport({ report, user, selfDescription, jobDescription }) {
  const html = buildReportHtml(report, { user, selfDescription, jobDescription });
  const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "networkidle0" });
  const pdfBuffer = await page.pdf({ format: "A4", printBackground: true, margin: { top: "20px", right: "20px", bottom: "20px", left: "20px" } });
  await browser.close();
  return pdfBuffer;
}

module.exports = { createPdfFromReport };